/* docs-site/skeleton/data.js
 * The page manifest — single source of truth for sidebar, paging, search.
 * See ../memory/02-content-shape.md for the schema.
 */
window.PAGES = [
  {
    id: "getting-started",
    title: "Getting started",
    group: "Getting Started",
    order: 1,
    summary: "Install the Acme SDK and verify it works with a single call.",
    body: [
      "# Getting started",
      "",
      "Install the Acme SDK from npm and verify it works with a single call.",
      "",
      "## Install",
      "",
      "Add the SDK to your project:",
      "",
      "```bash",
      "npm install @acme/sdk",
      "```",
      "",
      "Or with pnpm:",
      "",
      "```bash",
      "pnpm add @acme/sdk",
      "```",
      "",
      "## Verify",
      "",
      "Drop a one-line call into any TypeScript file:",
      "",
      "```ts",
      "import { acme } from \"@acme/sdk\";",
      "",
      "const ping = await acme.ping();",
      "console.log(ping);",
      "```",
      "",
      "If you see `{ ok: true }`, you're set."
    ].join("\n")
  },
  {
    id: "quick-start",
    title: "Quick start",
    group: "Getting Started",
    order: 2,
    summary: "Build a minimal Acme-backed feature end to end in five minutes.",
    body: [
      "# Quick start",
      "",
      "Build a minimal Acme-backed feature end to end in five minutes.",
      "",
      "## Configure the client",
      "",
      "Authenticate once with an API key:",
      "",
      "```ts",
      "import { createClient } from \"@acme/sdk\";",
      "",
      "export const acme = createClient({",
      "  apiKey: process.env.ACME_API_KEY!",
      "});",
      "```",
      "",
      "## Call an endpoint",
      "",
      "Use the typed methods:",
      "",
      "```ts",
      "const user = await acme.users.get(\"u_42\");",
      "```",
      "",
      "Errors throw — see the [errors guide](#errors) for the shape."
    ].join("\n")
  },
  {
    id: "errors",
    title: "Errors",
    group: "Guides",
    order: 1,
    summary: "How Acme errors are shaped and how to read them in TypeScript.",
    body: [
      "# Errors",
      "",
      "Acme errors are typed and discriminated by `kind`. Every thrown error extends `AcmeError`.",
      "",
      "## Shape",
      "",
      "```ts",
      "interface AcmeError {",
      "  kind: \"network\" | \"auth\" | \"rate_limit\" | \"validation\" | \"server\";",
      "  message: string;",
      "  requestId: string;",
      "  retryable: boolean;",
      "}",
      "```",
      "",
      "## Handling each kind",
      "",
      "- **network** — retryable; backoff per [retries guide](#retries).",
      "- **auth** — never retryable; surface to user.",
      "- **rate_limit** — retryable; honor `Retry-After`.",
      "- **validation** — never retryable; surface field-level errors.",
      "- **server** — retryable once; otherwise surface."
    ].join("\n")
  },
  {
    id: "retries",
    title: "Retries",
    group: "Guides",
    order: 2,
    summary: "When to retry, how to backoff, and how to cap.",
    body: [
      "# Retries",
      "",
      "Only retry errors marked `retryable: true`.",
      "",
      "## Backoff",
      "",
      "Exponential with jitter, capped at 5 attempts:",
      "",
      "```ts",
      "async function withRetry<T>(fn: () => Promise<T>): Promise<T> {",
      "  let lastErr: unknown;",
      "  for (let i = 0; i < 5; i++) {",
      "    try { return await fn(); } catch (e: any) {",
      "      if (!e?.retryable) throw e;",
      "      lastErr = e;",
      "      const delay = Math.min(2 ** i * 250, 4000) + Math.random() * 250;",
      "      await new Promise(r => setTimeout(r, delay));",
      "    }",
      "  }",
      "  throw lastErr;",
      "}",
      "```",
      "",
      "Use it at the call site, not the SDK — callers know which calls matter."
    ].join("\n")
  },
  {
    id: "auth",
    title: "Auth",
    group: "Guides",
    order: 3,
    summary: "Where API keys live, how to rotate, and how to scope.",
    body: [
      "# Auth",
      "",
      "Acme uses long-lived API keys scoped to a single environment.",
      "",
      "## Where keys live",
      "",
      "Environment variables on the server; **never** in the client bundle.",
      "",
      "```bash",
      "export ACME_API_KEY=\"sk_live_…\"",
      "```",
      "",
      "> Keys prefixed `sk_test_` are sandbox-only; they hit test data and never bill.",
      "",
      "## Rotation",
      "",
      "Generate a new key in the dashboard, deploy, then revoke the old one. Old keys remain valid for a 24h grace window."
    ].join("\n")
  },
  {
    id: "api-overview",
    title: "API overview",
    group: "API Reference",
    order: 1,
    summary: "Top-level shape of the Acme client surface.",
    body: [
      "# API overview",
      "",
      "The Acme client exposes three namespaces: `users`, `orgs`, and `events`.",
      "",
      "## Namespaces",
      "",
      "- `acme.users.*` — user records, identities, sessions.",
      "- `acme.orgs.*` — organizations, memberships, roles.",
      "- `acme.events.*` — append-only event log (read-only).",
      "",
      "## Types",
      "",
      "Every method returns a promise of a typed result. Top-level types:",
      "",
      "```ts",
      "type User = { id: string; email: string; orgId: string };",
      "type Org  = { id: string; name: string; plan: \"free\" | \"team\" | \"biz\" };",
      "type Event = { id: string; ts: number; kind: string; data: unknown };",
      "```",
      "",
      "---",
      "",
      "Detailed reference lives under `/api/users`, `/api/orgs`, `/api/events` in your hosted docs."
    ].join("\n")
  }
];
